### ISSUE TITLE
Adding modality to the Form Category and Form Access

### ISSUE THREAD

**Issue by RaziaMahmodi** [xlg8/APMIS-Project#625]
There is a need to record modality by cluster as campaign form data. This will allow users to review the planned cluster-level modality at the start of the campaign (pre-campaign) and what occurred during post-campaign. Users will typically import a file with this info as pre-campaign modality, then update that file during the campaign, and import the updated file as post-campaign modality. To accomplish this, we suggest:

- [x] 1. Add "Modality_Pre" and "Modality_Post" as form category in DB. 
- [x] 2. Add "Modality-Pre" and "Modality-Post" to the Users/Form Access.
- [x] 3. CCode in Modality data must be unique. User is allowed to enter one data row per cluster code (CCode). (Similar to the Admin form). 
- [x] 4. Importing updated data should be allowed to overwrite existing data. 

These cluster level modality forms will be created and assigned in the usual way and are not related to the campaign basics section. Assigned users should be able to open the record-level forms as usual in the web view if they wish to make a single edit for example. These data are used for comparison and calculation in the dashboard.

**Comment by RaziaMahmodi** [comment]
On Test Server:
**Task number 1:** when the forms are assigned to "MODALITY_POST" and "MODALITY_PRE" formcategory in DB, Campaign Basics/ All Campaign will be out of access. 

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/57d95994-0dab-4286-8908-9b0423973711)

**Comment by RaziaMahmodi** [comment]
About task number 3: user is able to enter multiple data records for one cluster. It must be unique. 

![Image](https://github.com/AFG-Polio-Data/APMIS-Project/assets/88741672/6ecf1635-c6f0-4594-9037-32ef2c30368a)

**Comment by omoluabidotcom** [comment]
Please utilize "Modality_Pre" and "Modality_Post" for the form category of forms, instead of "MODALITY_PRE" or "MODALITY_POST". This is what is available within the system currently. If there is a requirement to convert it to all uppercase, such changes can be readily implemented.
