### ISSUE TITLE
Dashboard updates

### ISSUE THREAD

**Issue by bnygren** [xlg8/APMIS-Project#683]
Per Slack, this should be schedule for Live for 16 August

**Summary**: There is a new dashboard in R Shiny that needs to be associated with APMIS. The new dashboard version incorporates intracampaign data and has a new hosting setup. The current ("old") dashboard content is thus no longer needed as it is not getting new data well and has accuracy problems. 

The new dashboard is hosted in shinyapps.io. Shinyapps.io cannot use APMIS's login credentials as the service will not filter based on IP of the requesting host (i.e., it cannot be set to only respond to APMIS's requests to load into an iframe, and ignore other, public requests). However, Shinyapps.io has its own authentication, so dashboard users will need to set up a username for the dashboard. This is not ideal, but is OK, because most dashboard users are national viewers and will not use APMIS, and they can save their login after the first time. The reason to switch to Shinyapps.io is the difficulty in keeping Shiny running reliably in Ubuntu on Lindode. Shinyapps.io has been reliable and is also set up to handle multiple concurrent users to improve performance. The dashboard data are pulled from the APMIS API daily to refresh the dashboard.

**Tasks**

- [x] A new dashboard URL should be chosen. It could be something like dashboard.afghanistan-apmis.com or afghanistan-apmis.com/dashboard
- [x] Shinyapps.io has some considerations working with a subdomain address: https://support.posit.co/hc/en-us/articles/11957171184791-Can-my-ShinyApps-io-custom-domain-use-SSL#:~:text=It%20is%20not%20currently%20possible,is%20always%20served%20over%20SSL  . Setting up the dashboard in its own iframe may be a solution based on the above
- [x] Once the new dashboard is set up to its own URL, the tabs in APMIS should be changed as followed: There should be one dashboard tab (called "Dashboard") that links to the new dashboard link which should open in its own tab. There should no longer be an "Analytic Dashboard" tab.
- [x] The old dashboard should no longer be available 
- [x] The default page that loads for users should be Campaign Data since Dashboard will be a link to an external page

**Comment by bnygren** [comment]
reformatted issue description for clarity and as task list

**Comment by bnygren** [comment]
This seems ready to be under review and closed

**Comment by RaziaMahmodi** [comment]
Hi @bnygren, I closed this issue based on your last comment.
